apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/artsiomkazachinskiy/tasks
    targetRevision: HEAD
    path: .
    helm:
      releaseName: prometheus-app
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 