global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus-app'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['app:8080'] # 'app' is the service name in docker-compose
                               # Docker Compose DNS will resolve 'app' to the container's IP.
