apiVersion: v1
kind: Secret
metadata:
  name: git-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/artsiomkazachinskiy/tasks  # Замените на URL вашего репозитория
  username: your-username  # Опционально, если репозиторий приватный
  password: your-token    # Опционально, если репозиторий приватный 