name: Docker Build and Versioning

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/docker/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Get last tag
        id: get-tag
        run: |

      - name: Bump version
        id: bump-version
        run: |

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push with version tag
        uses: docker/build-push-action@v5
        with:
          context: ./app/docker
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mytestapp:${{ steps.bump-version.outputs.new_tag }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/mytestapp:latest

      - name: Create Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ steps.bump-version.outputs.new_tag }}
          git push origin ${{ steps.bump-version.outputs.new_tag }}
