name: Update Docker Image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'app/.argocd-source-prometheus-app.yaml'  # Триггер только при изменении в папке src

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest image tag
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}/tags" | jq -r '.results[0].name')
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Update image tag in values.yaml
        run: |
          sed -i "s|tag:.*|tag: ${LATEST_TAG}|g" app/values.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update Docker image to ${{ env.LATEST_TAG }}"
          title: "chore: update Docker image to ${{ env.LATEST_TAG }}"
          body: |
            Automated PR to update Docker image tag to ${{ env.LATEST_TAG }}
          branch: update-docker-image
          base: main 
